Test Auth - 4

diff --git a/.github/workflows/ci-pipeline.yml b/.github/workflows/ci-pipeline.yml
--- a/.github/workflows/ci-pipeline.yml
+++ b/.github/workflows/ci-pipeline.yml
@@ -29,6 +29,18 @@ jobs:
         run: |
           export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
           export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          find . -type f -name '*.html' | while read HTMLFILE; do
+            HTMLFILESHORT=${HTMLFILE:2}
+            HTMLFILE_WITHOUT_INDEX=${HTMLFILESHORT::${#HTMLFILESHORT}-11}
+
+            aws s3 cp s3://app.bottlemarket.com.ar/${HTMLFILESHORT} \
+              s3://app.bottlemarket.com.ar/$HTMLFILE_WITHOUT_INDEX
+
+            if [ $? -ne 0 ]; then
+              echo "***** Failed renaming $HTMLFILESHORT"
+              exit 1
+            fi
+          done
           aws s3 sync packages/shop/out s3://app.bottlemarket.com.ar/ --exclude index.html --region us-east-1
           aws s3 cp packages/shop/out/index.html s3://app.bottlemarket.com.ar/ --metadata-directive REPLACE --cache-control max-age=0,no-cache,no-store,must-revalidate --content-type text/html --region us-east-1
       # - name: Build Admin Web
