Shop S3 upload to S3 - 1

diff --git a/.github/workflows/ci-pipeline.yml b/.github/workflows/ci-pipeline.yml
--- a/.github/workflows/ci-pipeline.yml
+++ b/.github/workflows/ci-pipeline.yml
@@ -19,10 +19,58 @@ jobs:
       - name: Install dependencies
         run: yarn install
 
-      - name: Build
+      - name: Build Shop Web
+        run: |
+        yarn build:shop
+        mv out/_next . # out/ contains only html files
+        mv out _out
+        mkdir -p out/builds/$GITHUB_SHA
+        mv _out/* out/builds/$GITHUB_SHA
+        rm -rf _out
+        mv _next out/
+
+      - name: Upload Shop Web
+        run: |
+        export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
+        export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
+        aws s3 cp ./out/_next s3://app.bottlemarket.com.ar/$GITHUB_REF/_next \
+          --cache-control immutable,max-age=100000000,public \
+          --acl public-read \
+          --recursive
+        aws s3 cp ./static/ s3://app.bottlemarket.com.ar/$GITHUB_REF/static/ \
+          --cache-control immutable,max-age=100000000,public \
+          --acl public-read \
+          --recursive
+        aws s3 cp ./out/builds s3://app.bottlemarket.com.ar/$GITHUB_REF/builds \
+          --cache-control max-age=0,no-cache \
+          --acl public-read \
+          --recursive
+        (cd out/builds &&
+        find . -type f -name '*.html' | while read HTMLFILE; do
+          HTMLFILESHORT=${HTMLFILE:2}
+          HTMLFILE_WITHOUT_INDEX=${HTMLFILESHORT::${#HTMLFILESHORT}-11}
+      
+          # cp /about/index.html to /about
+          aws s3 cp s3://app.bottlemarket.com.ar/$GITHUB_REF/builds/${HTMLFILESHORT} \
+            s3://app.bottlemarket.com.ar/$GITHUB_REF/builds/$HTMLFILE_WITHOUT_INDEX
+      
+          if [ $? -ne 0 ]; then
+            echo "***** Failed renaming build to app.bottlemarket.com.ar/$GITHUB_REF (html)"
+            exit 1
+          fi
+        done)
+
+      - name: Deploy Shop Web
+        run: |
+        aws s3 sync s3://app.bottlemarket.com.ar/$NAMESPACE/builds/$GITHUB_SHA s3://app.bottlemarket.com.ar/$GITHUB_REF/current \
+        --delete \
+        --cache-control max-age=0,no-cache \
+        --acl public-read
+
+      - name: Build API
         run: yarn build:api
 
-      - name: sam build
+      - name: Deploy API
         uses: eactisgrosso/aws-sam-action@v1
         with:
           node_version: 12.x
